### ISSUE TITLE
List All Builds of a Prerelease Version

### ISSUE THREAD

**Issue by orj** [ittybittyapps/appstoreconnect-cli#104]
# 🗣 Context

Get a list of builds of a specific prerelease version.

# 💬 Narrative

As a ...
I want ...
So that ...

# 📝 Notes

Covering this [API](https://developer.apple.com/documentation/appstoreconnectapi/list_all_builds_of_a_prerelease_version).

# 🎨 Design

_Provide design example, screenshot, text input/output etc_

# ✅ Acceptance Criteria

**GIVEN** ...
**WHEN** ...
**THEN** ...

# 🚫 Out of Scope

_Describe what is out of scope_

**Comment by DechengMa** [comment]
I think this was already implemented in #137 
Usage  `asc testflight builds list --filter-pre-release-versions 1.0.0`
