### ISSUE TITLE
Add a Beta Tester to Beta Groups

### ISSUE THREAD

**Issue by orj** [ittybittyapps/appstoreconnect-cli#109]
# 🗣 Context

Add one or more beta testers to a specific beta group.

# 💬 Narrative

As a user
I want add an existing beta tester to beta groups
So that so I can manage user access

# 📝 Notes

Covering this [API](https://developer.apple.com/documentation/appstoreconnectapi/add_a_beta_tester_to_beta_groups).

# 🎨 Design

```
asc testflight betatesters addgroup emailAddress groups...
asc testflight betagroup adduser emailAddresses...
```

# ✅ Acceptance Criteria

**GIVEN** ...
**WHEN** ...
**THEN** ...

**Comment by DechengMa** [comment]
duplicated of #72
