### ISSUE TITLE
Bug: You can not effectively filter beta testers by beta group

### ISSUE THREAD

**Issue by orj** [ittybittyapps/appstoreconnect-cli#169]
# 🌎 Environment

 - OS: macOS
 - Version/Release: master as of 7c7ecb554af1810a59501212828fb8ef8029ddca

# 💬 Description

Filtering by group name and app identifier is not allowed.

# 🦶 Reproduction Steps

1. `./asc testflight betatesters list --filter-group-names "XYZ" --filter-identifiers com.example.App1`

# 🤔 Expected Results

That the beta testers of the group "XYZ" for the app with the bundle id "com.example.App1" would be displayed.

A common use case for this command would be to show the users in a particular group for a particular app.

Without being able to filter by group name and app this command isn't very useful outside of listing all the beta-testers.

# 😲 Actual Results

The following error is printed:
```
Error: Only one of these relationship filters ('app-id/ bundle-id', 'group-name') can be applied.
```

**Comment by orj** [comment]
What I'm looking for is the equivalent of:
The API call [List All Beta Testers in a BetaGroup](https://developer.apple.com/documentation/appstoreconnectapi/list_all_beta_testers_in_a_betagroup)

**Comment by adamjcampbell** [comment]
@orj the API you listed isn't actually being called via this command. As such #176 has been raised. This command is for retrieving the entire set of testers and filtering from there. Such a thing could be implemented in this command via filling out multiple relationships and filtering down.

Do you think that is also worthwhile?
We also seem to have a limitation if relationships go over multiple pages we don't fetch all the relationship data at this time.

**Comment by Nafisa2020** [comment]
@adamjcampbell I have a question about the above comment about getting the entire set of beta testers..when I used list beta groups endpoint for the scenario where we input both app id and group name I also pass these as filters to the betagroup end point and mention beta testers as included..so does it actually brings all betatesters or based on the filters I passed (which are identifiers and group names) it gets only the relevant beta testers?

**Comment by orj** [comment]
> @orj the API you listed isn't actually being called via this command. 

Yes I realise that.  I was more point at it as an example of the API that does what I want.
