### ISSUE TITLE
Bug: Running `asc bundle-ids list` 

### ISSUE THREAD

**Issue by raven** [ittybittyapps/appstoreconnect-cli#193]
# 🌎 Environment

 - OS: macOS 
 - Version/Release: 0.1.0

# 💬 Description

Running `asc bundle-ids list` fails after some significant amount of delay.

`asc users` succeeds speedily ~3seconds

# 🦶 Reproduction Steps

`asc bundle-ids list`

# 🤔 Expected Results

A list of bundle ids

# 😲 Actual Results

After ~3mins20sec of non-responsiveness, macOS killed it with `bus error`

```sh
$ time asc bundle-ids list
[2]    21383 bus error  asc bundle-ids list
asc bundle-ids list  10.57s user 0.59s system 5% cpu 3:19.87 total
```
![image](https://user-images.githubusercontent.com/316931/84253687-934aa780-ab53-11ea-8fc6-4ff82a3ee003.png)

I can see whilst I am running `asc` that it is utilising networking:

![image](https://user-images.githubusercontent.com/316931/84253904-d86ed980-ab53-11ea-8d12-0cc0d790020a.png)

## 🌳 Logs

Where might I find those?

**Comment by raven** [comment]
Tell me what you need to help diagnose 👍

**Comment by adamjcampbell** [comment]
I also think it is most likely an issue with some output getting swallowed in a publisher chain and waiting on await.

The default timeout is `.distantFuture` but maybe it shouldn't be?
https://github.com/ittybittyapps/appstoreconnect-cli/blob/d8faf3989f55909d9b399576fbc348450a7d4137/Sources/AppStoreConnectCLI/Helpers/Publisher%2BHelpers.swift#L24

**Comment by raven** [comment]
> What role did you give your API Key
`developer`

>  also please try other commands to see if you get any similar issues.

- ✅  `asc users`
- ✅  `asc certificates list`
- ❌  `asc devices list`
- ✅ ❌  `asc profiles list` ( wow that was some output that flew past )
  - Exited with `1` status code
  - This failed differently than the original issue. The output streamed past, and then ended with:
  ```
  Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "included", intValue: nil), _JSONKey(stringValue: "Index 366", intValue: 366), CodingKeys(stringValue: "attributes", intValue: nil), CodingKeys(stringValue: "certificateType", intValue: nil)], debugDescription: "Cannot initialize CertificateType from invalid String value DEVELOPMENT", underlyingError: nil)).
   ```
- ✅  `asc testflight apps list`
- ✅  `asc testflight builds list` took a very long time to complete (`3164` builds)

**Comment by raven** [comment]
Would be great if there was some kind of messaging to stderr "This can take a long time..." or some other cli ux that indicated activity (`--verbose`, `ncurses` etc).

**Comment by orj** [comment]
@raven Thanks for giving this a whirl Pete. Much appreciated.

**Comment by DechengMa** [comment]
As https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/111 was merged this issue should be fixed

**Comment by raven** [comment]
Will there be a release to accomodate this fix?
