### ISSUE TITLE
Task: Configure SwiftLint to run during build

### ISSUE THREAD

**Issue by orj** [ittybittyapps/appstoreconnect-cli#52]
# ❕ Problem Statement

At the moment we don't have any linting being performed during build.

# 💬 Task Description

Configure the build process to run SwiftLint with appropriate rules.

# 👩‍🔧 Technical Design Notes

We want to be pretty strict with our rules so we have a consistent looking codebase.

**Comment by adamjcampbell** [comment]
Started trying to tackle this using a github action to run swiftlint and reviewdog here: https://github.com/Apple-Actions/action-swiftlint

**Comment by DechengMa** [comment]
Closed in #192
